require_relative '{{{nodeModulesRelativePath}}}/react-native/scripts/react_native_pods'
require_relative '{{{nodeModulesRelativePath}}}/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '{{{iosDeploymentTarget}}}'

{{#extraPodspecsSources}}
{{{.}}}
{{/extraPodspecsSources}}

{{#extraPodfileStatements}}
{{{.}}}
{{/extraPodfileStatements}}

target '{{{projectName}}}' do
  config = use_native_modules!

  use_react_native!(
    :path => "{{{nodeModulesRelativePath}}}/react-native"
  )

{{#extraPods}}
  {{{.}}}
{{/extraPods}}

  post_install do |installer|
    react_native_post_install(installer)

    # Workaround for FBReactNativeSpec dependency cycle issue
    # https://github.com/facebook/react-native/issues/31034#issuecomment-812564390
    # https://github.com/electrode-io/electrode-native-manifest/pull/217
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end

      # Workaround for CODE_SIGNING_ALLOWED changed in Xcode 14
      # https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1259231655
      # https://developer.apple.com/forums/thread/708659
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end

      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
end
